# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Paisajes Coloniales
email: paisajescoloniales@gmail.com
description: Redibujando los territorios andinos en el siglo XVII
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paisajescoloniales.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:
tagline: Redibujando los territorios andinos en el siglo XVII
twitter:
  username: Paisajescoloni1
  card: summary
logo: /assets/img/logo.png
image: /assets/img/logo-image.png

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: assets/css
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - Rakefile
#   - spec
#   - README.md



# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  paisajes: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'qatar_item' # the layout for the pages to use
    metadata:
      source: 'paisajes.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/paisajes' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      paisajes:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - author
          - location
          - label
          - _date
          - object_type
          - current_location

# --------------------------------------------------------------
